# Generated by Django 3.2.5 on 2021-07-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_broadcastnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='user',
        ),
    ]
