# Generated by Django 3.2.5 on 2021-07-30 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_broadcastnotification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noficationmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=45)),
                ('video', models.FileField(blank=True, upload_to='video/')),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
