# Generated by Django 3.2.5 on 2021-07-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_noficationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noficationmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
