# Generated by Django 3.2 on 2021-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_noficationmessage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BroadcastNotification',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='/image/image.jpg', null=True, upload_to='image/'),
        ),
        migrations.DeleteModel(
            name='Noficationmessage',
        ),
    ]
